# Generated by Django 3.1.6 on 2021-03-27 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20210327_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='experience',
            field=models.CharField(choices=[('Less than 1 year', 'Less than 1 year'), ('1 to 3 year', '1 to 3 year'), ('More than 3 year', 'More than 3 year')], default='More than 3 year', max_length=80, verbose_name='Experience'),
        ),
    ]
