# Generated by Django 3.1.6 on 2021-03-15 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(choices=[(0, 'Performance'), (1, 'Narrative'), (2, 'Concept'), (3, 'Lyric'), (4, 'Animated')])),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Singer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('singer_name', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('description', models.TextField()),
                ('number_played_movies', models.IntegerField()),
                ('total_awards', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='MusicVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist', models.CharField(max_length=50)),
                ('video_title', models.CharField(max_length=50)),
                ('director', models.CharField(max_length=30)),
                ('duration', models.FloatField()),
                ('issue_year', models.IntegerField()),
                ('video_genre', models.CharField(max_length=30)),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.genre')),
                ('singer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.singer')),
            ],
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('artist', models.CharField(max_length=50)),
                ('album_title', models.CharField(max_length=100)),
                ('album_genre', models.CharField(max_length=50)),
                ('album_logo', models.CharField(max_length=150)),
                ('music_video', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='music.musicvideo')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.genre')),
                ('singer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.singer')),
            ],
        ),
    ]
