# Generated by Django 3.1.6 on 2021-03-15 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='singer',
            name='age',
        ),
        migrations.AddField(
            model_name='singer',
            name='singer_birthdate',
            field=models.CharField(default=True, max_length=50),
            preserve_default=False,
        ),
    ]
