# Generated by Django 3.1.6 on 2021-03-15 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_auto_20210315_1506'),
    ]

    operations = [
        migrations.RenameField(
            model_name='singer',
            old_name='number_played_movies',
            new_name='number_songs',
        ),
    ]
